# Generated by Django 4.2.6 on 2023-11-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
