# Generated by Django 4.2.6 on 2023-11-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
