# Generated by Django 4.2.6 on 2023-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_movies_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
