# Generated by Django 4.2.6 on 2023-11-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='M_name',
            new_name='song_name',
        ),
    ]
