# Generated by Django 4.2.6 on 2023-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_detial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
    ]
