# Generated by Django 4.2.6 on 2023-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('visit', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
    ]
