# Generated by Django 4.2.6 on 2023-12-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('cc', models.CharField(max_length=25)),
                ('colour', models.CharField(max_length=25)),
            ],
        ),
    ]
